---
# cloud_controller_uri: api.vcap.me
service:
  name: uhurufs
  version: "0.9"
  description: 'Uhuru persistent filesystem service'
  plans: ['free']
  tags: ['uhurufs', 'uhurufs-0.9', 'Persistent filesystem service']
ip_route: localhost
#proxy:
#   host: proxy
#   port: 8080
#   keepalive: true
index: 0
token: "0xdeadbeef"
logging:
  level: debug
mbus: nats://localhost:4222
pid: /var/vcap/sys/run/uhurufs_service.pid
node_timeout: 20
plan_management:
  plans:
    free:
      low_water: 10
      high_water: 180
      #allow_over_provisioning: false

# z_interval: 30
# check_orphan_interval: 3600
# double_check_orphan_interval: 300
