---
capacity: 200
plan: free
local_db: sqlite3:/var/vcap/services/mongodb/mongodb_node.db
mbus: nats://localhost:4222
index: 0
base_dir: /var/vcap/services/mongodb/instances
ip_route: 127.0.0.1
logging:
  level: debug
mongod_log_dir: /var/vcap/sys/log/mongodb
pid: /var/vcap/sys/run/mongodb_node.pid
max_memory: 128
node_id: mongodb_node_free_1
mongod_path: mongod
mongorestore_path: mongorestore
port_range:
  first: 25001
  last: 45000
migration_nfs: /mnt/migration
# max_clients: 500
# z_interval: 30
# max_nats_payload: 1048576
