---
mbus: nats://localhost:4222
z_interval: 30
logging:
  level: debug
root: /mnt/appcloud
enable: true
wakeup_interval: 3600
rotation:
  max_days: 7
  cloud_controller_uri: api.vcap.me
  services:
    mongodb:
      version: "1.8"
      token: "0xdeadbeef"
    redis:
      version: "2.2"
      token: "0xdeadbeef"
    mysql:
      version: "5.1"
      token: "0xdeadbeef"

